packages:
  - 'projects/npm-packages/*'
  - 'projects/apps/hub/*'
  - 'projects/apps/personal/*'
  - 'projects/apps/content/*'
  - 'projects/apps/tools/*'
  - 'projects/apis/*'
  - 'projects/books/*'
  - 'projects/browser-extensions/*'
  - 'projects/ide-extensions/*'
  - 'projects/mcp-servers/*'
  - 'projects/skills/*'
